services:
  noripot:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    restart: unless-stopped
    working_dir: /noripot

    ports:
      - "4096:4096"
      - "2048:2048"

    volumes:
      - ./noripot/runtime:/noripot/runtime
      - ./noripot/scripts:/noripot/projects/scripts

    environment:
      NODE_ENV: production

    init: true
